
_           cycle ontop                   # 窗口 > 切换 置顶
_           script-message-to mpvnet edit-conf-file input.conf  # 配置 > 编辑 input.conf
MBTN_Right script-message-to mpvnet show-menu

# 播放列表：TAB 打开/关闭（走 playlistmanager 的 toggle 分支）
TAB         script-message playlistmanager show playlist toggle
