#使用默认皮肤
osc=no

# 记住上次播放位置，下次打开继续看
save-position-on-quit=no

# 运行 MPV 自动窗口最大化 yes代表最大化，no代表正常
#window-maximized=no

# 默认为系统原生窗口界面，启用此项使用无边框界面（去除 Windows 的窗口装饰）
#no-border                          

# 窗口置顶
#ontop                                   

# 开启硬件解码，解放你的CPU
# N卡使用专用解码器 nvdec，避免 d3d11va 在部分录屏/非规整文件上卡死
hwdec=nvdec

# 字幕默认样式（美观） sub-font(字体)，sub-font-size(字体大小)，sub-color(字幕颜色)，
#sub-border-color(字幕边框颜色)，sub-border-size(字幕边框大小)
sub-font="Microsoft YaHei"
sub-font-size=45
sub-color="#fbc420"
sub-border-color="#000000"
sub-border-size=2.5

# 截图保存路径和格式 
#screenshot-directory=~~/desktop/
screenshot-format=png

#高质量画面
profile=gpu-hq
